name: Release

on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build (skip tests for speed)
        run: mvn -B -ntp clean package -DskipTests

      - name: Locate loader/server jars
        id: findjars
        shell: bash
        run: |
          set -euo pipefail
          # Try module targets first
          LOADER=$(find . -type f -path "*/target/*" -name "rdfparquet-loader*.jar" | head -n1 || true)
          SERVER=$(find . -type f -path "*/target/*" -name "rdfparquet-server*.jar" | head -n1 || true)
          # Fall back to repo root if your build copies them there
          [[ -z "$LOADER" && -f rdfparquet-loader.jar ]] && LOADER="rdfparquet-loader.jar"
          [[ -z "$SERVER" && -f rdfparquet-server.jar ]] && SERVER="rdfparquet-server.jar"

          echo "LOADER=$LOADER" >> $GITHUB_OUTPUT
          echo "SERVER=$SERVER" >> $GITHUB_OUTPUT

          echo "Found:"
          echo "  loader: ${LOADER:-<none>}"
          echo "  server: ${SERVER:-<none>}"

          if [[ -z "$LOADER" || -z "$SERVER" ]]; then
            echo "ERROR: Could not find both jars." >&2
            exit 1
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: RDFParquet ${{ github.ref_name }}
          body: |
            Automated release for ${{ github.ref_name }}.
            Includes rdfparquet-loader.jar and rdfparquet-server.jar.
          files: |
            ${{ steps.findjars.outputs.LOADER }}
            ${{ steps.findjars.outputs.SERVER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
