name: build-and-release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build shaded jars
        run: mvn -B -DskipTests clean package

      - name: Create GitHub Release and upload jars
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rdfparquet-loader.jar
            rdfparquet-server.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

